name: Swift

on:
  push:
    branches: [ "feature/*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # üîç SwiftLint
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        continue-on-error: true

      # üõ† Xcode Build
      - name: Build
          working-directory: ./how-was-today
        run: xcodebuild -scheme how-was-today -destination 'platform=iOS Simulator,name=iPhone 14' clean build

      # ‚úÖ Xcode Test
      - name: Run tests
        working-directory: ./how-was-today
        run: xcodebuild -scheme how-was-today -destination 'platform=iOS Simulator,name=iPhone 14' test

      # üì¢ Slack Ïã§Ìå® ÏïåÎ¶º
      - name: Slack Notification (Failure)
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,message,ref,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()

      # üéâ Slack ÏÑ±Í≥µ ÏïåÎ¶º
      - name: Slack Notification (Success)
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,message,ref,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: success()
